### ISSUE TITLE
Add support for Environment records

### ISSUE THREAD

**Issue by sanmiguel** [basho-labs/mesos-erlang#29]
`erl_mesos_utils` library has support for creating e.g. `CommandInfo` records, but not the `Environment` records that they can contain. In `riak-mesos-scheduler` I created a simple-minded set of functions to do this, but I'd rather those were available in this library: https://github.com/basho-labs/riak-mesos-scheduler/blob/master/src/rms_erl_mesos_utils.erl

**Comment by platon** [comment]
Definitely it should be a part of the erl_mesos_utils.

**Comment by sanmiguel** [comment]
@platon did we ever do this? I know we talked about it, but I don't recall a PR.
